gems:
    - jekyll-language-plugin
    - jekyll-assets
    - jekyll-sitemap

language_data: data.lang.%%
language_includes_dir: _i18n

languages: ['es']

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'css', 'js', 'config.ru', 'vendor']

include: ['_i18n']

sass:
  sass_dir: css/_scss

assets:
  compress:
    css: default
    js: default

  autowrite: true

  assets:
    - "main.css"
    - "*.js"

  sources:
    - css
    - js

# ------------------------

# Build settings
markdown: kramdown

# Maps
maps:
  google:
    api_key: AIzaSyArBBEqgoRS4NIKBoFzXqM775z5Fw5Znu8

# Carousels
accessories:
  folder: "/images/accessories/"
  images:
    - url: "accessories01.jpg"
      name: "Accesorios1"
    - url: "accessories02.jpg"
      name: "Accesorios2"
    - url: "accessories03.jpg"
      name: "Accesorios3"
    - url: "accessories04.jpg"
      name: "Accesorios4"
    - url: "accessories05.jpg"
      name: "Accesorios5"
    - url: "accessories06.jpg"
      name: "Accesorios6"
    - url: "accessories07.jpg"
      name: "Accesorios7"
    - url: "accessories08.jpg"
      name: "Accesorios8"
    - url: "accessories09.jpg"
      name: "Accesorios9"
    - url: "accessories10.jpg"
      name: "Accesorios10"

babyboy:
  folder: "/images/babyboy/"
  images:
    - url: "babyboy01.jpg"
      name: "Bebe Niño1"
    - url: "babyboy02.jpg"
      name: "Bebe Niño2"
    - url: "babyboy03.jpg"
      name: "Bebe Niño3"
    - url: "babyboy04.jpg"
      name: "Bebe Niño4"
    - url: "babyboy05.jpg"
      name: "Bebe Niño5"
    - url: "babyboy06.jpg"
      name: "Bebe Niño6"
    - url: "babyboy07.jpg"
      name: "Bebe Niño7"
    - url: "babyboy08.jpg"
      name: "Bebe Niño8"
    - url: "babyboy09.jpg"
      name: "Bebe Niño9"
    - url: "babyboy10.jpg"
      name: "Bebe Niño10"

babygirl:
  folder: "/images/babygirl/"
  images:
    - url: "babygirl01.jpg"
      name: "Bebe Niña1"
    - url: "babygirl02.jpg"
      name: "Bebe Niña2"
    - url: "babygirl03.jpg"
      name: "Bebe Niña3"
    - url: "babygirl04.jpg"
      name: "Bebe Niña4"
    - url: "babygirl05.jpg"
      name: "Bebe Niña5"
    - url: "babygirl06.jpg"
      name: "Bebe Niña6"
    - url: "babygirl07.jpg"
      name: "Bebe Niña7"
    - url: "babygirl08.jpg"
      name: "Bebe Niña8"
    - url: "babygirl09.jpg"
      name: "Bebe Niña9"
    - url: "babygirl10.jpg"
      name: "Bebe Niña10"

boy:
  folder: "/images/boy/"
  images:
    - url: "boy01.png"
      name: "Niño1"
    - url: "boy02.png"
      name: "Niño2"
    - url: "boy03.png"
      name: "Niño3"
    - url: "boy04.jpg"
      name: "Niño4"
    - url: "boy05.jpg"
      name: "Niño5"
    - url: "boy06.jpg"
      name: "Niño6"
    - url: "boy07.jpg"
      name: "Niño7"
    - url: "boy08.jpg"
      name: "Niño8"
    - url: "boy09.jpg"
      name: "Niño9"
    - url: "boy10.jpg"
      name: "Niño10"

christening:
  folder: "/images/christening/"
  images:
    - url: "christening01.jpg"
      name: "Bautizo1"
    - url: "christening02.jpg"
      name: "Bautizo2"
    - url: "christening03.jpg"
      name: "Bautizo3"
    - url: "christening04.jpg"
      name: "Bautizo4"
    - url: "christening05.jpg"
      name: "Bautizo5"
    - url: "christening06.jpg"
      name: "Bautizo6"
    - url: "christening07.jpg"
      name: "Bautizo7"
    - url: "christening08.jpg"
      name: "Bautizo8"
    - url: "christening09.jpg"
      name: "Bautizo9"
    - url: "christening10.jpg"
      name: "Bautizo10"

communion:
  folder: "/images/communion/"
  images:
    - url: "communion01.jpg"
      name: "Comunión01"
    - url: "communion02.jpg"
      name: "Comunión02"
    - url: "communion03.jpg"
      name: "Comunión03"
    - url: "communion04.jpg"
      name: "Comunión04"
    - url: "communion05.jpg"
      name: "Comunión05"
    - url: "communion06.jpg"
      name: "Comunión06"
    - url: "communion07.jpg"
      name: "Comunión07"
    - url: "communion08.jpg"
      name: "Comunión08"
    - url: "communion09.jpg"
      name: "Comunión09"
    - url: "communion10.jpg"
      name: "Comunión10"
    - url: "communion11.jpg"
      name: "Comunión11"
    - url: "communion12.jpg"
      name: "Comunión12"
    - url: "communion13.jpg"
      name: "Comunión13"
    - url: "communion14.jpg"
      name: "Comunión14"
    - url: "communion15.jpg"
      name: "Comunión15"
    - url: "communion16.jpg"
      name: "Comunión16"
    - url: "communion17.jpg"
      name: "Comunión17"
    - url: "communion18.jpg"
      name: "Comunión18"
    - url: "communion19.jpg"
      name: "Comunión19"
    - url: "communion20.jpg"
      name: "Comunión20"
    - url: "communion21.jpg"
      name: "Comunión21"
    - url: "communion22.jpg"
      name: "Comunión22"
    - url: "communion23.jpg"
      name: "Comunión23"
    - url: "communion24.jpg"
      name: "Comunión24"
    - url: "communion25.jpg"
      name: "Comunión25"
    - url: "communion26.jpg"
      name: "Comunión26"
    - url: "communion27.jpg"
      name: "Comunión27"
    - url: "communion28.jpg"
      name: "Comunión28"
    - url: "communion29.jpg"
      name: "Comunión29"
    - url: "communion30.jpg"
      name: "Comunión30"
    - url: "communion31.jpg"
      name: "Comunión31"
    - url: "communion32.jpg"
      name: "Comunión32"
    - url: "communion33.jpg"
      name: "Comunión33"
    - url: "communion34.jpg"
      name: "Comunión34"
    - url: "communion35.jpg"
      name: "Comunión35"
    - url: "communion36.jpg"
      name: "Comunión36"
    - url: "communion37.jpg"
      name: "Comunión37"
    - url: "communion38.jpg"
      name: "Comunión38"
    - url: "communion39.jpg"
      name: "Comunión39"
    - url: "communion40.jpg"
      name: "Comunión40"
    - url: "communion41.jpg"
      name: "Comunión41"
    - url: "communion42.jpg"
      name: "Comunión42"

footwear:
  folder: "/images/footwear/"
  images:
    - url: "footwear01.jpg"
      name: "Calzado1"
    - url: "footwear02.jpg"
      name: "Calzado2"
    - url: "footwear03.jpg"
      name: "Calzado3"
    - url: "footwear04.jpg"
      name: "Calzado4"
    - url: "footwear05.jpg"
      name: "Calzado5"
    - url: "footwear06.jpg"
      name: "Calzado6"
    - url: "footwear07.jpg"
      name: "Calzado7"
    - url: "footwear08.jpg"
      name: "Calzado8"
    - url: "footwear09.jpg"
      name: "Calzado9"
    - url: "footwear10.jpg"
      name: "Calzado10"

gifts:
  folder: "/images/gifts/"
  images:
    - url: "gifts01.jpg"
      name: "Regalos1"
    - url: "gifts02.jpg"
      name: "Regalos2"
    - url: "gifts03.jpg"
      name: "Regalos3"
    - url: "gifts04.jpg"
      name: "Regalos4"
    - url: "gifts05.jpg"
      name: "Regalos5"
    - url: "gifts06.jpg"
      name: "Regalos6"
    - url: "gifts07.jpg"
      name: "Regalos7"
    - url: "gifts08.jpg"
      name: "Regalos8"
    - url: "gifts09.jpg"
      name: "Regalos9"
    - url: "gifts10.jpg"
      name: "Regalos10"

girl:
  folder: "/images/girl/"
  images:
    - url: "girl01.png"
      name: "Niña1"
    - url: "girl02.png"
      name: "Niña2"
    - url: "girl03.png"
      name: "Niña3"
    - url: "girl04.png"
      name: "Niña4"
    - url: "girl05.png"
      name: "Niña5"
    - url: "girl06.png"
      name: "Niña6"
    - url: "girl07.png"
      name: "Niña7"
    - url: "girl08.jpg"
      name: "Niña8"
    - url: "girl09.jpg"
      name: "Niña9"
    - url: "girl10.jpg"
      name: "Niña10"

wedding:
  folder: "/images/wedding/"
  images:
    - url: "wedding01.jpg"
      name: "Arras01"
    - url: "wedding02.jpg"
      name: "Arras02"
    - url: "wedding03.jpg"
      name: "Arras03"
    - url: "wedding04.jpg"
      name: "Arras04"
    - url: "wedding05.jpg"
      name: "Arras05"
    - url: "wedding06.jpg"
      name: "Arras06"
    - url: "wedding07.jpg"
      name: "Arras07"
    - url: "wedding08.png"
      name: "Arras08"
    - url: "wedding09.png"
      name: "Arras09"
    - url: "wedding10.png"
      name: "Arras10"
    - url: "wedding11.png"
      name: "Arras11"
    - url: "wedding12.png"
      name: "Arras12"
    - url: "wedding13.png"
      name: "Arras13"
    - url: "wedding14.png"
      name: "Arras14"
    - url: "wedding15.png"
      name: "Arras15"