gems:
    - jekyll-language-plugin
    - jekyll-assets
    - jekyll-sitemap

language_data: data.lang.%%
language_includes_dir: _i18n

languages: ['es']

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'css', 'js', 'config.ru', 'vendor']

include: ['_i18n']

sass:
  sass_dir: css/_scss

assets:
  compress:
    css: default
    js: default

  autowrite: true

  assets:
    - "main.css"
    - "*.js"

  sources:
    - css
    - js

# ------------------------

# Build settings
markdown: kramdown

# Maps
maps:
  google:
    api_key: AIzaSyArBBEqgoRS4NIKBoFzXqM775z5Fw5Znu8

# Carousels
accessories:
  folder: "/images/accessories/"
  images:
    - url: "accessories01.jpg"
      name: "Accesorios 01"

babyboy:
  folder: "/images/babyboy/"
  images:
    - url: "babyboy01.jpg"
      name: "Bebe Niño 01"
    - url: "babyboy02.jpg"
      name: "Bebe Niño 02"
    - url: "babyboy03.jpg"
      name: "Bebe Niño 03"

babygirl:
  folder: "/images/babygirl/"
  images:
    - url: "babygirl01.jpg"
      name: "Bebe Niña 01"
    - url: "babygirl02.jpg"
      name: "Bebe Niña 02"
    - url: "babygirl03.jpg"
      name: "Bebe Niña 03"
    - url: "babygirl04.jpg"
      name: "Bebe Niña 04"
    - url: "babygirl05.jpg"
      name: "Bebe Niña 05"

boy:
  folder: "/images/boy/"
  images:
    - url: "boy01.png"
      name: "Niño 01"
    - url: "boy02.png"
      name: "Niño 02"
    - url: "boy03.png"
      name: "Niño 03"

christening:
  folder: "/images/christening/"
  images:
    - url: "christening01.jpg"
      name: "Bautizo 01"

communion:
  folder: "/images/communion/"
  images:
    - url: "communion01.jpg"
      name: "Comunión 01"
    - url: "communion02.jpg"
      name: "Comunión 02"
    - url: "communion03.jpg"
      name: "Comunión 03"
    - url: "communion04.jpg"
      name: "Comunión 04"
    - url: "communion05.jpg"
      name: "Comunión 05"
    - url: "communion06.jpg"
      name: "Comunión 06"
    - url: "communion07.jpg"
      name: "Comunión 07"
    - url: "communion08.jpg"
      name: "Comunión 08"
    - url: "communion09.jpg"
      name: "Comunión 09"
    - url: "communion10.jpg"
      name: "Comunión 10"
    - url: "communion11.jpg"
      name: "Comunión 11"
    - url: "communion12.jpg"
      name: "Comunión 12"
    - url: "communion13.jpg"
      name: "Comunión 13"
    - url: "communion14.jpg"
      name: "Comunión 14"
    - url: "communion15.jpg"
      name: "Comunión 15"
    - url: "communion16.jpg"
      name: "Comunión 16"
    - url: "communion17.jpg"
      name: "Comunión 17"
    - url: "communion18.jpg"
      name: "Comunión 18"
    - url: "communion19.jpg"
      name: "Comunión 19"
    - url: "communion20.jpg"
      name: "Comunión 20"
    - url: "communion21.jpg"
      name: "Comunión 21"
    - url: "communion22.jpg"
      name: "Comunión 22"
    - url: "communion23.jpg"
      name: "Comunión 23"
    - url: "communion24.jpg"
      name: "Comunión 24"
    - url: "communion25.jpg"
      name: "Comunión 25"
    - url: "communion26.jpg"
      name: "Comunión 26"
    - url: "communion27.jpg"
      name: "Comunión 27"
    - url: "communion28.jpg"
      name: "Comunión 28"
    - url: "communion29.jpg"
      name: "Comunión 29"
    - url: "communion30.jpg"
      name: "Comunión 30"
    - url: "communion31.jpg"
      name: "Comunión 31"
    - url: "communion32.jpg"
      name: "Comunión 32"
    - url: "communion33.jpg"
      name: "Comunión 33"
    - url: "communion34.jpg"
      name: "Comunión 34"
    - url: "communion35.jpg"
      name: "Comunión 35"
    - url: "communion36.jpg"
      name: "Comunión 36"
    - url: "communion37.jpg"
      name: "Comunión 37"
    - url: "communion38.jpg"
      name: "Comunión 38"
    - url: "communion39.jpg"
      name: "Comunión 39"
    - url: "communion40.jpg"
      name: "Comunión 40"
    - url: "communion41.jpg"
      name: "Comunión 41"
    - url: "communion42.jpg"
      name: "Comunión 42"

footwear:
  folder: "/images/footwear/"
  images:
    - url: "footwear01.jpg"
      name: "Calzado 01"
    - url: "footwear02.jpg"
      name: "Calzado 02"
    - url: "footwear03.jpg"
      name: "Calzado 03"
    - url: "footwear04.jpg"
      name: "Calzado 04"
    - url: "footwear05.jpg"
      name: "Calzado 05"

gifts:
  folder: "/images/gifts/"
  images:
    - url: "gifts01.jpg"
      name: "Regalos 01"

girl:
  folder: "/images/girl/"
  images:
    - url: "girl01.png"
      name: "Niña 01"
    - url: "girl02.png"
      name: "Niña 02"
    - url: "girl03.png"
      name: "Niña 03"
    - url: "girl04.png"
      name: "Niña 04"
    - url: "girl05.png"
      name: "Niña 05"
    - url: "girl06.png"
      name: "Niña 06"
    - url: "girl07.png"
      name: "Niña 07"

wedding:
  folder: "/images/wedding/"
  images:
    - url: "wedding01.jpg"
      name: "Arras 01"
    - url: "wedding02.jpg"
      name: "Arras 02"
    - url: "wedding03.jpg"
      name: "Arras 03"
    - url: "wedding04.jpg"
      name: "Arras 04"
    - url: "wedding05.jpg"
      name: "Arras 05"
    - url: "wedding06.jpg"
      name: "Arras 06"
    - url: "wedding07.jpg"
      name: "Arras 07"
    - url: "wedding08.png"
      name: "Arras 08"
    - url: "wedding09.png"
      name: "Arras 09"
    - url: "wedding10.png"
      name: "Arras 10"
    - url: "wedding11.png"
      name: "Arras 11"
    - url: "wedding12.png"
      name: "Arras 12"
    - url: "wedding13.png"
      name: "Arras 13"
    - url: "wedding14.png"
      name: "Arras 14"
    - url: "wedding15.png"
      name: "Arras 15"
    - url: "wedding16.jpg"
      name: "Arras 16"
    - url: "wedding17.jpg"
      name: "Arras 17"
    - url: "wedding18.jpg"
      name: "Arras 18"
    - url: "wedding19.jpg"
      name: "Arras 19"
    - url: "wedding20.jpg"
      name: "Arras 20"
    - url: "wedding21.jpg"
      name: "Arras 21"
    - url: "wedding22.jpg"
      name: "Arras 22"
    - url: "wedding23.jpg"
      name: "Arras 23"
    - url: "wedding24.jpg"
      name: "Arras 24"
