gems:
    - jekyll-assets
    - jekyll-sitemap

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'css', 'js', 'config.ru', 'vendor']

include: ['_i18n']

sass:
  sass_dir: css/_scss

assets:
  compress:
    css: default
    js: default

  autowrite: true

  assets:
    - "main.css"
    - "*.js"

  sources:
    - css
    - js

# ------------------------

# Build settings
markdown: kramdown

# Maps
maps:
  google:
    api_key: AIzaSyArBBEqgoRS4NIKBoFzXqM775z5Fw5Znu8

# Texts

main:
  title: "MamaCarlota"
  titleTag: "MamaCarlota"
  description: "MamaCarlota - Tienda de bebés y niños en barrio Salamanca (Madrid)"
  keywords: "mama carlota narvaez"
terms:
  title: "Aviso Legal"
cookies:
  title: Política de cookies
  titleTag: "Política de cookies"

home:
  title: "MamaCarlota"
  homeTitle: "Tienda de bebés y niños de 0 a 16 años"
  description1: "Especialistas en ceremonia, comunión y bautizo. También confección a media. Complementos y calzado."
  description2: "Más de 20 años de experiencia en moda (bebés, niños y ceremonia), nos hace ser una empresa familiar, diferente y original."
  phone: "91 042 12 45"
  title_tab: "INICIO"
  url: "/"

  presentation: "Ropa de ceremonia para niños en Madrid y confección de prendas de gran calidad"
  p1: "En MamaCarlota todas las prendas son fabricadas en España con el máximo control y cuidado; cumpliendo nuestro objetivo y asegurando tanto calidad como acabados exquisitos."
  p2: "Diseñamos desde vestidos para ceremonia o eventos, hasta prendas básicas e informales, siempre manteniendo nuestro estilo propio y cuidando hasta el mínimo detalle."
  p3_1: "Te invitamos a que entres y veas toda la moda infantil que hemos seleccionado para ti, porque si buscas algo diferente, "
  p3_2: "aquí"
  p3_3: " lo vas a encontrar."

  mapsTitle: "¿Dónde estamos ubicados?"
  address: "Calle de Narváez 13, 28009 Madrid"

catalog:
  title_1: "Catálogo de "
  title_2: "MamaCarlota"
  subtitle: "En nuestro catálogo encontrará la más amplia variedad."

  title_tab: "CATÁLOGO"
  url: "/catalogo"

  accessories:
    title: "Accesorios"
    url: "/accesorios"
    image: "/images/accessories/accessories.jpg"

  babyboy:
    title: "Bebé niño"
    url: "/bebe-nino"
    image: "/images/babyboy/babyboy.jpg"

  babygirl:
    title: "Bebé niña"
    url: "/bebe-nina"
    image: "/images/babygirl/babygirl.jpg"

  boy:
    title: "Niño"
    url: "/nino"
    image: "/images/boy/boy.jpg"

  christening:
    title: "Bautizo"
    url: "/bautizo"
    image: "/images/christening/christening.jpg"

  communion:
    title: "Comunión"
    url: "/comunion"
    image: "/images/communion/communion.jpg"

  footwear:
    title: "Calzado"
    url: "/calzado"
    image: "/images/footwear/footwear.jpg"

  gifts:
    title: "Regalos"
    url: "/regalos"
    image: "/images/gifts/gifts.jpg"

  girl:
    title: "Niña"
    url: "/nina"
    image: "/images/girl/girl.jpg"

  wedding:
    title: "Arras"
    url: "/arras"
    image: "/images/wedding/wedding.jpg"

# Sections
accessories:
  title: "Accesorios"
  subtitle: "Diademas, turbantes, lazos, gomas de pelo y mucho más."
  folder: "/images/accessories/"
  images:
    - url: "accessories.jpg"
      name: "Accesorios 01"
    - url: "accessories02.jpg"
      name: "Accesorios 02"
    - url: "accessories01.jpg"
      name: "Accesorios 03"

babyboy:
  title: "Bebé niño"
  subtitle: "De 0 a 3 años."
  folder: "/images/babyboy/"
  images:
    - url: "babyboy.jpg"
      name: "Bebé Niño 01"
    - url: "babyboy14.jpg"
      name: "Bebé Niño 02"
    - url: "babyboy13.jpg"
      name: "Bebé Niño 03"
    - url: "babyboy12.jpg"
      name: "Bebé Niño 04"
    - url: "babyboy11.jpg"
      name: "Bebé Niño 05"
    - url: "babyboy10.jpg"
      name: "Bebé Niño 06"
    - url: "babyboy09.jpg"
      name: "Bebé Niño 07"
    - url: "babyboy08.jpg"
      name: "Bebé Niño 08"
    - url: "babyboy07.jpg"
      name: "Bebé Niño 09"
    - url: "babyboy06.jpg"
      name: "Bebé Niño 10"
    - url: "babyboy05.jpg"
      name: "Bebé Niño 11"
    - url: "babyboy04.jpg"
      name: "Bebé Niño 12"
    - url: "babyboy03.jpg"
      name: "Bebé Niño 13"
    - url: "babyboy02.jpg"
      name: "Bebé Niño 14"
    - url: "babyboy01.jpg"
      name: "Bebé Niño 15"

babygirl:
  title: "Bebé niña"
  subtitle: "De 0 a 3 años."
  folder: "/images/babygirl/"
  images:
    - url: "babygirl.jpg"
      name: "Bebé Niña 01"
    - url: "babygirl13.jpg"
      name: "Bebé Niña 02"
    - url: "babygirl12.jpg"
      name: "Bebé Niña 03"
    - url: "babygirl11.jpg"
      name: "Bebé Niña 04"
    - url: "babygirl10.jpg"
      name: "Bebé Niña 05"
    - url: "babygirl09.jpg"
      name: "Bebé Niña 06"
    - url: "babygirl08.jpg"
      name: "Bebé Niña 07"
    - url: "babygirl07.jpg"
      name: "Bebé Niña 08"
    - url: "babygirl06.jpg"
      name: "Bebé Niña 09"
    - url: "babygirl05.jpg"
      name: "Bebé Niña 10"
    - url: "babygirl04.jpg"
      name: "Bebé Niña 11"
    - url: "babygirl03.jpg"
      name: "Bebé Niña 12"
    - url: "babygirl02.jpg"
      name: "Bebé Niña 13"
    - url: "babygirl01.jpg"
      name: "Bebé Niña 14"

boy:
  title: "Niño"
  subtitle: "De 3 a 14 años."
  folder: "/images/boy/"
  images:
    - url: "boy.jpg"
      name: "Niño 01"
    - url: "boy11.jpg"
      name: "Niño 02"
    - url: "boy10.jpg"
      name: "Niño 03"
    - url: "boy09.jpg"
      name: "Niño 04"
    - url: "boy08.jpg"
      name: "Niño 05"
    - url: "boy07.jpg"
      name: "Niño 06"
    - url: "boy06.jpg"
      name: "Niño 07"
    - url: "boy05.jpg"
      name: "Niño 08"
    - url: "boy04.jpg"
      name: "Niño 09"
    - url: "boy03.jpg"
      name: "Niño 10"
    - url: "boy02.jpg"
      name: "Niño 11"
    - url: "boy01.jpg"
      name: "Niño 12"

christening:
  title: "Bautizo"
  subtitle: "Conjuntos para niño y niña."
  folder: "/images/christening/"
  images:
    - url: "christening.jpg"
      name: "Bautizo 01"
    - url: "christening06.jpg"
      name: "Bautizo 02"
    - url: "christening05.jpg"
      name: "Bautizo 03"
    - url: "christening04.jpg"
      name: "Bautizo 04"
    - url: "christening03.jpg"
      name: "Bautizo 05"
    - url: "christening02.jpg"
      name: "Bautizo 06"
    - url: "christening01.jpg"
      name: "Bautizo 07"

communion:
  title: "Comunión"
  subtitle: "Trajes, vestidos, y coronas de flores."
  folder: "/images/communion/"
  images:
    - url: "communion.jpg"
      name: "Comunión 01"
    - url: "communion48.jpg"
      name: "Comunión 02"
    - url: "communion47.jpg"
      name: "Comunión 03"
    - url: "communion46.jpg"
      name: "Comunión 04"
    - url: "communion45.jpg"
      name: "Comunión 05"
    - url: "communion44.jpg"
      name: "Comunión 06"
    - url: "communion43.jpg"
      name: "Comunión 07"
    - url: "communion42.jpg"
      name: "Comunión 08"
    - url: "communion41.jpg"
      name: "Comunión 09"
    - url: "communion40.jpg"
      name: "Comunión 10"
    - url: "communion39.jpg"
      name: "Comunión 11"
    - url: "communion38.jpg"
      name: "Comunión 12"
    - url: "communion37.jpg"
      name: "Comunión 13"
    - url: "communion36.jpg"
      name: "Comunión 14"
    - url: "communion35.jpg"
      name: "Comunión 15"
    - url: "communion34.jpg"
      name: "Comunión 16"
    - url: "communion33.jpg"
      name: "Comunión 17"
    - url: "communion32.jpg"
      name: "Comunión 18"
    - url: "communion31.jpg"
      name: "Comunión 19"
    - url: "communion30.jpg"
      name: "Comunión 20"
    - url: "communion29.jpg"
      name: "Comunión 21"
    - url: "communion28.jpg"
      name: "Comunión 22"
    - url: "communion27.jpg"
      name: "Comunión 23"
    - url: "communion26.jpg"
      name: "Comunión 24"
    - url: "communion25.jpg"
      name: "Comunión 25"
    - url: "communion24.jpg"
      name: "Comunión 26"
    - url: "communion23.jpg"
      name: "Comunión 27"
    - url: "communion22.jpg"
      name: "Comunión 28"
    - url: "communion21.jpg"
      name: "Comunión 29"
    - url: "communion20.jpg"
      name: "Comunión 30"
    - url: "communion19.jpg"
      name: "Comunión 31"
    - url: "communion18.jpg"
      name: "Comunión 32"
    - url: "communion17.jpg"
      name: "Comunión 33"
    - url: "communion16.jpg"
      name: "Comunión 34"
    - url: "communion15.jpg"
      name: "Comunión 35"
    - url: "communion14.jpg"
      name: "Comunión 36"
    - url: "communion13.jpg"
      name: "Comunión 37"
    - url: "communion12.jpg"
      name: "Comunión 38"
    - url: "communion11.jpg"
      name: "Comunión 39"
    - url: "communion10.jpg"
      name: "Comunión 40"
    - url: "communion09.jpg"
      name: "Comunión 41"
    - url: "communion08.jpg"
      name: "Comunión 42"
    - url: "communion07.jpg"
      name: "Comunión 43"
    - url: "communion06.jpg"
      name: "Comunión 44"
    - url: "communion05.jpg"
      name: "Comunión 45"
    - url: "communion04.jpg"
      name: "Comunión 46"
    - url: "communion03.jpg"
      name: "Comunión 47"
    - url: "communion02.jpg"
      name: "Comunión 48"
    - url: "communion01.jpg"
      name: "Comunión 49"

footwear:
  title: "Calzado"
  subtitle: "Zapatos, calcetines y medias."
  folder: "/images/footwear/"
  images:
    - url: "footwear.jpg"
      name: "Calzado 01"
    - url: "footwear06.jpg"
      name: "Calzado 02"
    - url: "footwear05.jpg"
      name: "Calzado 03"
    - url: "footwear04.jpg"
      name: "Calzado 04"
    - url: "footwear03.jpg"
      name: "Calzado 05"
    - url: "footwear02.jpg"
      name: "Calzado 06"
    - url: "footwear01.jpg"
      name: "Calzado 07"

gifts:
  title: "Regalos"
  subtitle: "Cestas personalizadas."
  folder: "/images/gifts/"
  images:
    - url: "gifts.jpg"
      name: "Regalos 01"
    - url: "gifts06.jpg"
      name: "Regalos 02"
    - url: "gifts05.jpg"
      name: "Regalos 03"
    - url: "gifts04.jpg"
      name: "Regalos 04"
    - url: "gifts03.jpg"
      name: "Regalos 05"
    - url: "gifts02.jpg"
      name: "Regalos 06"
    - url: "gifts01.jpg"
      name: "Regalos 07"

girl:
  title: "Niña"
  subtitle: "De 3 a 14 años."
  folder: "/images/girl/"
  images:
    - url: "girl.jpg"
      name: "NNiña 01"
    - url: "girl27.jpg"
      name: "Niña 02"
    - url: "girl26.jpg"
      name: "Niña 03"
    - url: "girl25.jpg"
      name: "Niña 04"
    - url: "girl24.jpg"
      name: "Niña 05"
    - url: "girl23.jpg"
      name: "Niña 06"
    - url: "girl22.jpg"
      name: "Niña 07"
    - url: "girl21.jpg"
      name: "Niña 08"
    - url: "girl20.jpg"
      name: "Niña 09"
    - url: "girl19.jpg"
      name: "Niña 10"
    - url: "girl18.jpg"
      name: "Niña 11"
    - url: "girl17.png"
      name: "Niña 12"
    - url: "girl16.jpg"
      name: "Niña 13"
    - url: "girl15.jpg"
      name: "Niña 14"
    - url: "girl14.jpg"
      name: "Niña 15"
    - url: "girl13.jpg"
      name: "Niña 16"
    - url: "girl12.jpg"
      name: "Niña 17"
    - url: "girl11.jpg"
      name: "Niña 18"
    - url: "girl10.png"
      name: "Niña 19"
    - url: "girl09.png"
      name: "Niña 20"
    - url: "girl08.jpg"
      name: "Niña 21"
    - url: "girl07.jpg"
      name: "Niña 22"
    - url: "girl06.jpg"
      name: "Niña 23"
    - url: "girl05.jpg"
      name: "Niña 24"
    - url: "girl04.jpg"
      name: "Niña 25"
    - url: "girl03.jpg"
      name: "Niña 26"
    - url: "girl02.jpg"
      name: "Niña 27"
    - url: "girl01.jpg"
      name: "Niña 28"


wedding:
  title: "Arras"
  subtitle: "Vestidos y trajes."
  folder: "/images/wedding/"
  images:
    - url: "wedding.jpg"
      name: "Arras 01"
    - url: "wedding26.jpg"
      name: "Arras 02"
    - url: "wedding25.jpg"
      name: "Arras 03"
    - url: "wedding24.jpg"
      name: "Arras 04"
    - url: "wedding23.jpg"
      name: "Arras 05"
    - url: "wedding22.jpg"
      name: "Arras 06"
    - url: "wedding21.jpg"
      name: "Arras 07"
    - url: "wedding20.jpg"
      name: "Arras 08"
    - url: "wedding19.jpg"
      name: "Arras 09"
    - url: "wedding18.jpg"
      name: "Arras 10"
    - url: "wedding17.jpg"
      name: "Arras 11"
    - url: "wedding16.jpg"
      name: "Arras 12"
    - url: "wedding15.jpg"
      name: "Arras 13"
    - url: "wedding14.jpg"
      name: "Arras 14"
    - url: "wedding13.jpg"
      name: "Arras 15"
    - url: "wedding12.jpg"
      name: "Arras 16"
    - url: "wedding11.jpg"
      name: "Arras 17"
    - url: "wedding10.jpg"
      name: "Arras 18"
    - url: "wedding09.jpg"
      name: "Arras 19"
    - url: "wedding08.jpg"
      name: "Arras 20"
    - url: "wedding07.jpg"
      name: "Arras 21"
    - url: "wedding06.jpg"
      name: "Arras 22"
    - url: "wedding05.jpg"
      name: "Arras 23"
    - url: "wedding04.jpg"
      name: "Arras 24"
    - url: "wedding03.jpg"
      name: "Arras 25"
    - url: "wedding02.jpg"
      name: "Arras 26"
    - url: "wedding01.jpg"
      name: "Arras 27"