gems:
    - jekyll-assets
    - jekyll-sitemap

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'css', 'js', 'config.ru', 'vendor']

include: ['_i18n']

sass:
  sass_dir: css/_scss

assets:
  compress:
    css: default
    js: default

  autowrite: true

  assets:
    - 'main.css'
    - '*.js'

  sources:
    - css
    - js

# ------------------------

# Build settings
markdown: kramdown

# Maps
maps:
  google:
    api_key: AIzaSyArBBEqgoRS4NIKBoFzXqM775z5Fw5Znu8

# Texts

main:
  title: 'MamaCarlota'
  titleTag: 'MamaCarlota'
  description: 'MamaCarlota - Tienda de bebés y niños en barrio Salamanca (Madrid)'
  keywords: 'mama carlota narvaez'
terms:
  title: 'Aviso Legal'
cookies:
  title: Política de cookies
  titleTag: 'Política de cookies'

home:
  title: 'MamaCarlota'
  homeTitle: 'Tienda de bebés y niños de 0 a 16 años'
  description1: 'Especialistas en ceremonia, comunión y bautizo. También confección a media. Complementos y calzado.'
  description2: 'Más de 20 años de experiencia en moda (bebés, niños y ceremonia), nos hace ser una empresa familiar, diferente y original.'
  phone: '91 042 12 45'
  open: 'Lunes a Sábado de 10:00 - 14:00 y 17:00 - 20:30'
  title_tab: 'INICIO'
  url: '/'

  presentation: 'Ropa de ceremonia para niños en Madrid y confección de prendas de gran calidad'
  p1: 'En MamaCarlota todas las prendas son fabricadas en España con el máximo control y cuidado; cumpliendo nuestro objetivo y asegurando tanto calidad como acabados exquisitos.'
  p2: 'Diseñamos desde vestidos para ceremonia o eventos, hasta prendas básicas e informales, siempre manteniendo nuestro estilo propio y cuidando hasta el mínimo detalle.'
  p3_1: 'Te invitamos a que entres y veas toda la moda infantil que hemos seleccionado para ti, porque si buscas algo diferente, '
  p3_2: 'aquí'
  p3_3: ' lo vas a encontrar.'

  mapsTitle: '¿Dónde estamos ubicados?'
  address: 'Calle de Narváez 13, 28009 Madrid'

catalog:
  title_1: 'Catálogo de '
  title_2: 'MamaCarlota'
  subtitle: 'En nuestro catálogo encontrarás la más amplia variedad.'

  title_tab: 'CATÁLOGO'
  url: '/catalogo'

promo:
  title: 'ReBaJaS'
  subtitle_1: 'Hasta el'
  subtitle_2: '50'
  subtitle_3: '%'
  subtitle_4: 'dto.'
  advice: 'Excepto artículos de continuidad y nueva colección'

# birthday:
#   title: '¡ Estamos de Aniversario !'
#   subtitle: 'Por muchos años más como este'

# Sections

accessories:
  title: 'Accesorios'
  subtitle: 'Diademas, turbantes, lazos, gomas de pelo y mucho más.'
  url: '/accesorios'
  image: '/images/accessories/0000.jpg'

babyboy:
  title: 'Bebé niño'
  subtitle: 'De 0 a 3 años.'
  url: '/bebe-nino'
  image: '/images/babyboy/0000.jpg'

babycare:
  title: 'Canastilla/Puericultura'
  subtitle: 'Todo lo que necesitas para tu bebé.'
  url: '/canastilla-puericultura'
  image: '/images/babycare/0000.jpg'

babygirl:
  title: 'Bebé niña'
  subtitle: 'De 0 a 3 años.'
  url: '/bebe-nina'
  image: '/images/babygirl/0000.jpg'

boy:
  title: 'Niño'
  subtitle: 'De 3 a 14 años.'
  url: '/nino'
  image: '/images/boy/0000.jpg'

christening:
  title: 'Bautizo'
  subtitle: 'Conjuntos para niño y niña.'
  url: '/bautizo'
  image: '/images/christening/0000.jpg'

communionboy:
  title: 'Comunión niño'
  subtitle: 'Trajes y complementos.'
  url: '/comunion-nino'
  image: '/images/communionboy/0000.jpg'

communiongirl:
  title: 'Comunión niña'
  subtitle: 'Vestidos, complementos y coronas de flores.'
  url: '/comunion-nina'
  image: '/images/communiongirl/0000.jpg'

footwear:
  title: 'Calzado'
  subtitle: 'Zapatos, calcetines y medias.'
  url: '/calzado'
  image: '/images/footwear/0000.jpg'

gifts:
  title: 'Regalos'
  subtitle: 'Cestas personalizadas.'
  url: '/regalos'
  image: '/images/gifts/0000.jpg'

girl:
  title: 'Niña'
  subtitle: 'De 3 a 14 años.'
  url: '/nina'
  image: '/images/girl/0000.jpg'

newcollection:
  title: 'Nueva colección'
  subtitle: 'Para estar siempre a la última.'
  url: '/nueva-coleccion'
  image: '/images/newcollection/0000.jpg'

pajamas:
  title: 'Pijamas'
  subtitle: 'Lo mejor para dormir cómodo.'
  url: '/pijamas'
  image: '/images/pajamas/0000.jpg'

swimwear:
  title: 'Trajes de baño'
  subtitle: 'Bañadores.'
  url: '/ropa-de-bano'
  image: '/images/swimwear/0000.jpg'

wedding:
  title: 'Arras'
  subtitle: 'Vestidos y trajes.'
  url: '/arras'
  image: '/images/wedding/0000.jpg'

help:
  slice: 'Deslice las imágenes'

ref: 'Referencia'