gems:
    - jekyll-language-plugin
    - jekyll-assets
    - jekyll-sitemap

language_data: data.lang.%%
language_includes_dir: _i18n

languages: ['es']

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'css', 'js', 'config.ru', 'vendor']

include: ['_i18n']

sass:
  sass_dir: css/_scss

assets:
  compress:
    css: default
    js: default

  autowrite: true

  assets:
    - "main.css"
    - "*.js"

  sources:
    - css
    - js

# ------------------------

# Build settings
markdown: kramdown

# Maps
maps:
  google:
    api_key: AIzaSyArBBEqgoRS4NIKBoFzXqM775z5Fw5Znu8

# Carousels
accessories:
  folder: "/images/accessories/"
  images:
    - url: "accessories01.jpg"
      name: "Titulo1"
    - url: "accessories02.jpg"
      name: "Titulo2"
    - url: "accessories03.jpg"
      name: "Titulo3"
    - url: "accessories04.jpg"
      name: "Titulo4"
    - url: "accessories05.jpg"
      name: "Titulo5"
    - url: "accessories06.jpg"
      name: "Titulo6"
    - url: "accessories07.jpg"
      name: "Titulo7"
    - url: "accessories08.jpg"
      name: "Titulo8"
    - url: "accessories09.jpg"
      name: "Titulo9"
    - url: "accessories10.jpg"
      name: "Titulo10"

babyboy:
  folder: "/images/babyboy/"
  images:
    - url: "babyboy01.jpg"
      name: "Titulo1"
    - url: "babyboy02.jpg"
      name: "Titulo2"
    - url: "babyboy03.jpg"
      name: "Titulo3"
    - url: "babyboy04.jpg"
      name: "Titulo4"
    - url: "babyboy05.jpg"
      name: "Titulo5"
    - url: "babyboy06.jpg"
      name: "Titulo6"
    - url: "babyboy07.jpg"
      name: "Titulo7"
    - url: "babyboy08.jpg"
      name: "Titulo8"
    - url: "babyboy09.jpg"
      name: "Titulo9"
    - url: "babyboy10.jpg"
      name: "Titulo10"

babygirl:
  folder: "/images/babygirl/"
  images:
    - url: "babygirl01.jpg"
      name: "Titulo1"
    - url: "babygirl02.jpg"
      name: "Titulo2"
    - url: "babygirl03.jpg"
      name: "Titulo3"
    - url: "babygirl04.jpg"
      name: "Titulo4"
    - url: "babygirl05.jpg"
      name: "Titulo5"
    - url: "babygirl06.jpg"
      name: "Titulo6"
    - url: "babygirl07.jpg"
      name: "Titulo7"
    - url: "babygirl08.jpg"
      name: "Titulo8"
    - url: "babygirl09.jpg"
      name: "Titulo9"
    - url: "babygirl10.jpg"
      name: "Titulo10"

boy:
  folder: "/images/boy/"
  images:
    - url: "boy01.jpg"
      name: "Titulo1"
    - url: "boy02.jpg"
      name: "Titulo2"
    - url: "boy03.jpg"
      name: "Titulo3"
    - url: "boy04.jpg"
      name: "Titulo4"
    - url: "boy05.jpg"
      name: "Titulo5"
    - url: "boy06.jpg"
      name: "Titulo6"
    - url: "boy07.jpg"
      name: "Titulo7"
    - url: "boy08.jpg"
      name: "Titulo8"
    - url: "boy09.jpg"
      name: "Titulo9"
    - url: "boy10.jpg"
      name: "Titulo10"

christening:
  folder: "/images/christening/"
  images:
    - url: "christening01.jpg"
      name: "Titulo1"
    - url: "christening02.jpg"
      name: "Titulo2"
    - url: "christening03.jpg"
      name: "Titulo3"
    - url: "christening04.jpg"
      name: "Titulo4"
    - url: "christening05.jpg"
      name: "Titulo5"
    - url: "christening06.jpg"
      name: "Titulo6"
    - url: "christening07.jpg"
      name: "Titulo7"
    - url: "christening08.jpg"
      name: "Titulo8"
    - url: "christening09.jpg"
      name: "Titulo9"
    - url: "christening10.jpg"
      name: "Titulo10"

communion:
  folder: "/images/communion/"
  images:
    - url: "communion01.jpg"
      name: "Comunión01"
    - url: "communion02.jpg"
      name: "Comunión02"
    - url: "communion03.jpg"
      name: "Comunión03"
    - url: "communion04.jpg"
      name: "Comunión04"
    - url: "communion05.jpg"
      name: "Comunión05"
    - url: "communion06.jpg"
      name: "Comunión06"
    - url: "communion07.jpg"
      name: "Comunión07"
    - url: "communion08.jpg"
      name: "Comunión08"
    - url: "communion09.jpg"
      name: "Comunión09"
    - url: "communion10.jpg"
      name: "Comunión10"

footwear:
  folder: "/images/footwear/"
  images:
    - url: "footwear01.jpg"
      name: "Titulo1"
    - url: "footwear02.jpg"
      name: "Titulo2"
    - url: "footwear03.jpg"
      name: "Titulo3"
    - url: "footwear04.jpg"
      name: "Titulo4"
    - url: "footwear05.jpg"
      name: "Titulo5"
    - url: "footwear06.jpg"
      name: "Titulo6"
    - url: "footwear07.jpg"
      name: "Titulo7"
    - url: "footwear08.jpg"
      name: "Titulo8"
    - url: "footwear09.jpg"
      name: "Titulo9"
    - url: "footwear10.jpg"
      name: "Titulo10"

gifts:
  folder: "/images/gifts/"
  images:
    - url: "gifts01.jpg"
      name: "Titulo1"
    - url: "gifts02.jpg"
      name: "Titulo2"
    - url: "gifts03.jpg"
      name: "Titulo3"
    - url: "gifts04.jpg"
      name: "Titulo4"
    - url: "gifts05.jpg"
      name: "Titulo5"
    - url: "gifts06.jpg"
      name: "Titulo6"
    - url: "gifts07.jpg"
      name: "Titulo7"
    - url: "gifts08.jpg"
      name: "Titulo8"
    - url: "gifts09.jpg"
      name: "Titulo9"
    - url: "gifts10.jpg"
      name: "Titulo10"

girl:
  folder: "/images/girl/"
  images:
    - url: "girl01.jpg"
      name: "Titulo1"
    - url: "girl02.jpg"
      name: "Titulo2"
    - url: "girl03.jpg"
      name: "Titulo3"
    - url: "girl04.jpg"
      name: "Titulo4"
    - url: "girl05.jpg"
      name: "Titulo5"
    - url: "girl06.jpg"
      name: "Titulo6"
    - url: "girl07.jpg"
      name: "Titulo7"
    - url: "girl08.jpg"
      name: "Titulo8"
    - url: "girl09.jpg"
      name: "Titulo9"
    - url: "girl10.jpg"
      name: "Titulo10"

wedding:
  folder: "/images/wedding/"
  images:
    - url: "wedding01.jpg"
      name: "Arras01"
    - url: "wedding02.jpg"
      name: "Arras02"
    - url: "wedding03.jpg"
      name: "Arras03"
    - url: "wedding04.jpg"
      name: "Arras04"
    - url: "wedding05.jpg"
      name: "Arras05"
    - url: "wedding06.jpg"
      name: "Arras06"
    - url: "wedding07.jpg"
      name: "Arras07"
    - url: "wedding08.jpg"
      name: "Arras08"
    - url: "wedding09.jpg"
      name: "Arras09"
    - url: "wedding10.jpg"
      name: "Arras10"